### ISSUE TITLE
selectedCountry in directive scope should be optional

### ISSUE THREAD

**Issue by dmbjsn** [Ahimta/bc-phone-number#14]
Hi,

Using angular 1.5.x, I've experienced a breaking change using this otherwise great directive.

`scope.selectedCountry` becomes undefined in `scope.$watch()` causing number not to be formatted and flag not to be shown on currently selected country. The attribute should be assigned to scope as optional because it is not defined in the template:

``` javascript
directive('bcPhoneNumber', function() {
    return {
        scope: {
            preferredCountriesCodes: '@preferredCountries',
            defaultCountryCode: '@defaultCountry',
            selectedCountry: '=?' // Changed from '='
            // Omitted attributes 
        }
    }
}
```

**Comment by SavePointSam** [comment]
Thanks for posting this @dmbjsn. I was about to start pulling my hair out from the undefined error.
