### ISSUE TITLE
Exclude demo code from source

### ISSUE THREAD

**Issue by jtormey** [Ahimta/bc-phone-number#2]
https://github.com/Ahimta/phone-number/blob/master/src/js/phone-number.js#L4-L7

`'MainCtrl'` in phone-number.js is only used for the demo and therefore isn't necessary in the src. I think it would be better to have a `/demo` directory for demo-related code like this.

**Comment by ahimta** [comment]
@jtormey good point.
For now it is easier to just keep it as is for development purposes.
I will move it from phone-number.js, eventually :)
The same apply for index.html too.

In addition to renaming the module and directive name (using `bc` prefix for example) and many more changes.

I will make many more changes in the [near future too](https://github.com/blockchain/My-Wallet-V3-Frontend/issues/152#issuecomment-145963574)
