### ISSUE TITLE
Better error message if dependencies are not loaded

### ISSUE THREAD

**Issue by Sjors** [Ahimta/bc-phone-number#3]
If I "forget" to load a dependency Javascript, I get a console error message like this:

`Cannot read property 'getCountryByIso2Code' of undefined`

It would be better if you check for the presence of dependencies and throw an error like:

`bc-countries not found, did you forget to load the Javascript?`

Also in the README, you should probably add instructions to add required script tags to index.html or a Grunt task.

**Comment by ahimta** [comment]
I personally use [wiredep](https://github.com/taptapship/wiredep).
It automatically injects your bower dependencies in the correct order.

I use it [here](https://github.com/Ahimta/bc-phone-number/blob/84ebec4c15e57de0280c85c2750b13f2ce1c9b0e/demo/index.html#L8-L19)
