### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by Sjors** [Ahimta/bc-phone-number#5]
I'm trying to include your component here:
https://github.com/blockchain/My-Wallet-V3-Frontend/pull/171

It's not throwing error messages, so I think I got all the dependencies.

It shows the correct phone number on load, so that's good:
<img width="428" alt="schermafbeelding 2015-10-13 om 10 56 07" src="https://cloud.githubusercontent.com/assets/10217/10445265/bda76ff8-71a2-11e5-9f8a-0565a054a414.png">

However I'm not seeing the flags, even though flags@2x.png does get loaded. 

It adds a plus sign whenever I type a new number, but it doesn't add spaces and dashes.

I can't access the validity state (see also #4); I set scope.status.isValid to null on load. It is set to false and stays that way.

The little white thing on the left looks weird too.

My guess is that I'm doing something wrong :-)

**Comment by ahimta** [comment]
Sorry it's mostly my fault.
You have to be careful with the [path of flags](https://github.com/Ahimta/bc-css-flags#usage), it may not be the issue though.
`preferred-countries` are expected to be space-separated (e.g: `us ca gb`), sorry about that :)

Strangely enough, Bootstrap depends on jQuery. You can see that in their bower.json file, as well as
the beginning of their `bootstrap/dist/js/bootstrap.js`.
This means that consequently, both bc-phone-number and ui-bootstrap also depend on jQuery.
So in this case you need to include jQuery and bootstrap.js.

In general, managing Javascript dependencies can be tricky.
One reason is that Javascript treats reference errors as exceptions, meaning that if you have a code
that catches an exception, it will work even if your referencing undefined variables or almost any other
language error.

If you still have the same error then it may have something to do with Angular scopes;
they can be tricky sometimes.

I'd strongly suggest that you use [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep)
and [grunt-usemin](https://github.com/yeoman/grunt-usemin).

Note that v5.0.1 now supports ngModel validation (e.g: myForm.number.$valid).

**Comment by Sjors** [comment]
The nice thing about ui.bootstrap is that it doesn't use the Bootstrap javascript; they rewrote everything in native AngularJS. So it does not depend on jQuery: https://github.com/angular-ui/bootstrap-bower/blob/master/bower.json

In your code you're depending on the `bootstrap` Bower package. You should change that to `angular-bootstrap`, see [here](https://github.com/angular-ui/bootstrap#install-with-bower).

Can you release a new build that uses angular-bootstrap and let me know? I'll try again (and I'll fix the comma separated list).

I don't think the flags file location is a problem; my Grunt script copies it to `/build/img` and the CSS is in `/build/css`. The browser loads the @2x image successfully (it would throw a 404 if the location was wrong).

**Comment by ahimta** [comment]
v5.0.3 now uses angular-bootstrap.

**Comment by Sjors** [comment]
Thanks, getting there... 

The dropdown now shows a list of countries, so that's working. The preferred countries show up on top (you should probably add a separator line). When I type a (partial) phone number it selects the right country:

<img width="420" alt="schermafbeelding 2015-10-14 om 10 14 05" src="https://cloud.githubusercontent.com/assets/10217/10473289/6b67b382-725c-11e5-9eda-f3b91a78bbb5.png">

But it still marks all phone numbers as invalid: `scope.mobileForm.$invalid` is `true` and `scope.mobileForm.$error.phoneNumber` exists. It's not adding spaces and dashes to the number either:

<img width="405" alt="schermafbeelding 2015-10-14 om 10 19 44" src="https://cloud.githubusercontent.com/assets/10217/10473369/28d2d3d4-725d-11e5-8304-a0e14851f60c.png">

It's also still not showing the flags, even though they download:
<img width="1042" alt="schermafbeelding 2015-10-14 om 10 05 50" src="https://cloud.githubusercontent.com/assets/10217/10473212/3791a352-725b-11e5-9a0b-112dca037b7c.png">

I updated my code on Github: blockchain/My-Wallet-V3-Frontend#171

If you like, you can try it for yourself by cloning blockchain/My-Wallet-V3-Frontend, checking out the bye-jquery branch. Install and run the server, create a new wallet and then going to Settings -> Preferences to set a mobile number.

**Comment by ahimta** [comment]
I added some comments on [commit page](https://github.com/blockchain/My-Wallet-V3-Frontend/commit/e5293808cc7f22d7d31a8a4aee293c27ce17bc24)

You can see the results of some changes below.
You may also need to make other changes, using your knowledge of My-Wallet-V3-Frontend
for better results.

![blockchain-bc-phone-number-divider](https://cloud.githubusercontent.com/assets/3470403/10478901/5bdf8dd8-7269-11e5-92f0-64b2a8249289.png)
![blockchain-bc-phone-number-invalid](https://cloud.githubusercontent.com/assets/3470403/10478902/5c0ed890-7269-11e5-870c-0447cc378779.png)
![blockchain-bc-phone-number-valid](https://cloud.githubusercontent.com/assets/3470403/10478903/5c22be82-7269-11e5-8efd-1558bdffcb8b.png)

**Comment by Sjors** [comment]
That worked, thanks! I'll have to adjust a few things in our own CSS.

One more thing (this might be our CSS though): can you remove the separator between the flag and the dropdown and the separator between the dropdown and the number? 

<img width="164" alt="schermafbeelding 2015-10-15 om 09 38 19" src="https://cloud.githubusercontent.com/assets/10217/10503469/7e6d635e-7320-11e5-91fd-3d531460a069.png">

See the original component:
<img width="109" alt="schermafbeelding 2015-10-15 om 09 36 02" src="https://cloud.githubusercontent.com/assets/10217/10503451/364312e0-7320-11e5-94f1-c452ebe5fba0.png">

**Comment by ahimta** [comment]
v5.0.4 removes the separator between the flag and the caret.
![bc-phone-number-focus](https://cloud.githubusercontent.com/assets/3470403/10504558/7f350622-730a-11e5-9bdb-9eff8b1ddc51.png)
![bc-phone-number-single-button](https://cloud.githubusercontent.com/assets/3470403/10504559/7f7552d6-730a-11e5-8fe2-c6420faf3381.png)

However, removing the separator between the button and the input element is more tricky and will take more time to get right.

**Comment by Sjors** [comment]
Thanks, I don't think that second seperator is a huge issue.
