### ISSUE TITLE
How to change the phone number programmatically?

### ISSUE THREAD

**Issue by Sjors** [Ahimta/bc-phone-number#7]
I got everything working in our project except one thing: once the input field contains a phone number, the user can change it, but I can't change it programatically.

There's two places where I need to do this:

1 - When the user presses cancel in the form:
https://github.com/blockchain/My-Wallet-V3-Frontend/blob/bye-jquery/assets/js/directives/configure-mobile-number.js.coffee#L43-L47

Next time they open the form, it still shows the last change they made.

2 - When the user doesn't have a phone number yet and I set it to the default country code:
https://github.com/blockchain/My-Wallet-V3-Frontend/blob/bye-jquery/assets/js/directives/configure-mobile-number.js.coffee#L31-L37
This second issue might go away with #6 though.

**Comment by ahimta** [comment]
v5.0.5 fixes #6 and #7

**Comment by Sjors** [comment]
Thanks for those changes!
